### ISSUE TITLE
Doesn't work on international flights

### ISSUE THREAD

**Issue by pyro2927** [pyro2927/SouthwestCheckin#4]
International flights appear to require passport information to be entered before they are booked.  No known API endpoints to submit this information at this time (mobile devices force you to go to web for checkin)

**Comment by brettphillips05** [comment]
I recently used this on an international flight and it was successful for me but not for my wife and father in law. Turns out, they did not have their "emergency contact" information filled out. I discovered this all can filled out before the flight checkin by entering in the information on the `Manage Flight` section of the reservation. This is found by navigating to the URL with the same information provided in the script

```
https://www.southwest.com/air/manage-reservation/view.html?confirmationNumber=[CONFIRMATION_NUMBER]&passengerFirstName=[FIRST_NAME]&passengerLastName=[LAST_NAME]
```

Once on this page, you can check that the passport information and emergency contact information is entered in. I figured this out and used the script for our flight back home... worked flawlessly for everyone.

I think I will submit a PR to update the README with this information, if that will be helpful for others.

BTW - THANK YOU, this script is amazing!
